{
  "type": "record",
  "name": "EventEnvelope",
  "namespace": "com.bitrockteam.kafkanuts.contracts",
  "fields": [
    {"name": "eventId", "type": "string"},
    {"name": "eventType", "type": "string"},
    {"name": "eventVersion", "type": "int"},
    {"name": "aggregateId", "type": "string"},
    {"name": "occurredAt", "type": {"type": "long", "logicalType": "timestamp-millis"}},
    {"name": "producer", "type": "string"},
    {"name": "correlationId", "type": ["null", "string"], "default": null},
    {"name": "causationId", "type": ["null", "string"], "default": null},
    {"name": "schemaFingerprint", "type": "string"},
    {"name": "payload", "type": "bytes"},
    {"name": "tenant", "type": "string", "default": "default"}
  ]
}
